name: prosecho

services:
  app:
    build: .
    command: sleep infinity
    environment:
      PGHOST: postgres
      PGPASSWORD: postgres
      PGUSER: postgres
    volumes:
      - ..:/prosecho:cached
    ports:
      - "127.0.0.1:3100:3000"
  postgres:
    image: docker.io/library/postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
