default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV["PGPASSWORD"] %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  schema_dump: ../config/schema.rb

development:
  <<: *default
  database: prosecho_development

test:
  <<: *default
  database: prosecho_test

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "prosecho_production") %>
